export { default as Home } from './home/home'
export { default as Markets } from './markets/markets'
export { default as AboutUs } from './aboutUs/aboutUs'
export { default as ContactUs } from './contactUs/contactUs'
export { default as CryptoConverter } from './crytpoConverter/cryptoConverter'
export { default as Login } from './auth/login/login'
export { default as Register } from './auth/register/register'
export { default as CryptoForecast } from './cryptoForecast/cryptoForecast'
